CREATE TABLE AUTHOR
(
    AUTHORID            smallint,
    AUTHORNAME          char(10),
    AUTHORTYPE          char(4),
    FIELD               varchar(30),
    ARTICLE             smallint,
 
    CONSTRAINT PK_AUTHORID PRIMARY KEY (AUTHORID)
)
 
CREATE TABLE AUTHOR_TYPE
(
    AU_TYPEID           char(4),
    TYPENAME            char(10),
 
    CONSTRAINT PK_AUTYPEID PRIMARY KEY (AU_TYPEID)
)
 
CREATE TABLE ARTICLE
(
    ARTICLEID            smallint,
    ARTICLETITLE         char(10),
    ARTICLETYPE          char(4),
    AUTHORID             smallint,
    VIEWS_COUNT          smallint,
    LIKES_COUNT          smallint,
 
    CONSTRAINT PK_ARTICLEID PRIMARY KEY (ARTICLEID)
)
 
CREATE TABLE ARTICLE_TYPE
(
    AR_TYPEID           char(4),
    TYPENAME            char(10),
 
    CONSTRAINT PK_ARTYPEID PRIMARY KEY (AR_TYPEID)
)
--INPUT FOR TABLE AUTHOR
INSERT INTO AUTHOR VALUES(1, 'Kevin La', 'AU01', NULL, NULL)
INSERT INTO AUTHOR(AUTHORID, AUTHORNAME, AUTHORTYPE) VALUES(2, 'Taco Nguyen', 'AU01')
INSERT INTO AUTHOR(AUTHORNAME, AUTHORID, AUTHORTYPE) VALUES('Brian Vu', 3, 'AU01')
INSERT INTO AUTHOR VALUES(74, 'Rye Nguyen', 'AU01', 'C++, Data Structure', NULL)
INSERT INTO AUTHOR VALUES(70, 'Amy Le', 'AU01', 'C++', NULL)
INSERT INTO AUTHOR VALUES(6, 'Dat Hoang Tien', 'AU02', NULL, NULL)
INSERT INTO AUTHOR VALUES(9, 'Tran Danh', 'AU02', NULL, NULL)
INSERT INTO AUTHOR VALUES(61, 'Tai Du Phat', 'AU01', NULL, NULL)
INSERT INTO AUTHOR VALUES(71, 'Hieu Nguyen Minh', 'AU02', NULL, NULL)
INSERT INTO AUTHOR VALUES(108, 'Hoa Dinh', 'AU01', NULL, NULL)
INSERT INTO AUTHOR VALUES(107, 'Jason Bui', 'AU01', NULL, NULL)
 
--INPUT FOR TABLE AUTHOR_TYPE
INSERT INTO AUTHOR_TYPE VALUES ('AU01', 'Periodic Author')
INSERT INTO AUTHOR_TYPE VALUES ('AU02', 'Free Author')
 
--INPUT FOR TABLE ARTICLE
INSERT INTO ARTICLE VALUES (1, 'Stdio Coding Convention - Level 1', 'AR10', 1, NULL, NULL, 15/7/2014)
INSERT INTO ARTICLE VALUES (2, 'Quan Ly Bo Nho Trong Cocos2d-x', 'AR05', 2, NULL, NULL, 29/9/2014)
INSERT INTO ARTICLE VALUES (3, 'Phat Hien Memory Leak Voi VLD', 'AR01', 3, NULL, NULL, 13/10/2014)
INSERT INTO ARTICLE VALUES (4, 'Pointer Trong C++', 'AR01', 74, NULL, NULL, 10/8/2014)
INSERT INTO ARTICLE VALUES (5, 'Preprocessor Va #include Directive', 'AR01', 70, NULL, NULL, 28/7/2014)
INSERT INTO ARTICLE VALUES (6, 'C++11 - Smart Pointer - Quan Ly Tai Nguyen', 'AR01', 6, NULL, NULL, 6/10/2014)
INSERT INTO ARTICLE VALUES (7, 'Ban Chat Cua Bien Trong C/C++', 'AR01', 9, NULL, NULL, 27/5/2014)
INSERT INTO ARTICLE VALUES (8, 'Template Trong C++', 'AR01', 61, NULL, NULL, 3/6/2014)
INSERT INTO ARTICLE VALUES (9, 'Thao Tac Voi Constant Trong C++', 'AR01', 71, NULL, NULL, 17/9/2014)
INSERT INTO ARTICLE VALUES (10, 'Tim Hieu Va Tao Tai Lieu XML Dau Tien', 'AR04', 108, NULL, NULL, 16/9/2014)
INSERT INTO ARTICLE VALUES (11, 'Xu Ly Thoi Gian Trong PHP', 'AR03', 107, NULL, NULL, 27/9/2014)
 
--INPUT FOR TABLE ARTICLE_TYPE
INSERT INTO ARTICLE_TYPE VALUES ('AR01', 'C/C++')
INSERT INTO ARTICLE_TYPE VALUES ('AR02', 'C#')
INSERT INTO ARTICLE_TYPE VALUES ('AR03', 'PHP')
INSERT INTO ARTICLE_TYPE VALUES ('AR04', 'XML')
INSERT INTO ARTICLE_TYPE VALUES ('AR05', 'Cocos2D-x')
INSERT INTO ARTICLE_TYPE VALUES ('AR06', 'Visual Studio')
INSERT INTO ARTICLE_TYPE VALUES ('AR07', 'Math')
INSERT INTO ARTICLE_TYPE VALUES ('AR08', 'Data Structure')
INSERT INTO ARTICLE_TYPE VALUES ('AR09', 'Experience')
INSERT INTO ARTICLE_TYPE VALUES ('AR10', 'Stdio Experience')